language: swift
osx_image: xcode11
before_install: rvm use $RVM_RUBY_VERSION
install: bundle install --without=documentation --path ../travis_bundle_dir
script:

  - set -o pipefail

  - xcodebuild clean build build-for-testing -project MusicNotationCore/MusicNotationCore.xcodeproj -scheme MusicNotationCoreMac -sdk macosx | xcpretty
  - xcodebuild test-without-building -project MusicNotationCore/MusicNotationCore.xcodeproj -scheme MusicNotationCoreMac -sdk macosx | xcpretty
  - xcodebuild build -project MusicNotationCore/MusicNotationCore.xcodeproj -scheme MusicNotationCoreiOS -sdk iphoneos | xcpretty
  - xcodebuild build -project MusicNotationCore/MusicNotationCore.xcodeproj -scheme MusicNotationCoreTV -sdk appletvos | xcpretty
  - xcodebuild build -project MusicNotationCore/MusicNotationCore.xcodeproj -scheme MusicNotationCoreWatch -sdk watchos | xcpretty
after_success:
  - bundle exec slather
  - bash <(curl -s https://codecov.io/bash) -f vendor/tests/coverage/cobertura.xml -X coveragepy -X gcov -X xcode
notifications:
  slack: musicnotationswift:GAuOCY6YxRaZHrDvGRXRF9Im
  email: false
