language: swift
osx_image: xcode11.3
script:

  - set -o pipefail

  - swift package clean
  - swift build --build-tests
  - swift test --enable-code-coverage
  - xcrun llvm-cov export -format="lcov" .build/debug/MusicNotationCorePackageTests.xctest/Contents/MacOS/MusicNotationCorePackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
after_success:
  - bash <(curl -s https://codecov.io/bash) -Z -f info.lcov
notifications:
  slack: musicnotationswift:GAuOCY6YxRaZHrDvGRXRF9Im
  email: false
