language: objective-c
osx_image: xcode7.3
script: 
  - xctool -workspace ./MusicNotation.xcworkspace -scheme MusicNotationKit build test -sdk macosx10.11 GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - ls -al /Users/travis/Library/Developer/Xcode/DerivedData
  - find "/Users/travis/Library/Developer/Xcode/DerivedData" -name '*.gcda' -exec gcov -pbcu {} +
  - bash <(curl -s https://codecov.io/bash)
